// Generates src/contract.gen.ts from contract/v1/schema.json (pinned copy of upstream
// contracts/public-engine/v1; see contract/PROVENANCE.md).
//
//   node scripts/generate-types.mjs          write the file
//   node scripts/generate-types.mjs --check  exit 1 if the file is stale
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const schemaPath = new URL("contract/v1/schema.json", root);
const outPath = new URL("src/contract.gen.ts", root);

export function generate(schema) {
  const lines = [
    "// Code generated by scripts/generate-types.mjs from",
    "// contracts/public-engine/v1/schema.json. DO NOT EDIT.",
    "",
    `export const CONTRACT_SCHEMA = ${JSON.stringify(schema["x-contractSchema"])};`,
    `export const CONTRACT_VERSION = ${JSON.stringify(schema["x-contractVersion"])};`,
    "",
    `export const ERROR_CODES = ${JSON.stringify(Object.keys(schema["x-errorCodes"]))} as const;`,
    "export type ContractErrorCode = (typeof ERROR_CODES)[number];",
    "",
    "/** Semantic reasoning profiles, in contract order (EngineInfo.defaultReasoningProfile enum). */",
    `export const REASONING_PROFILES = ${JSON.stringify(reasoningProfiles(schema))} as const;`,
    "export type ReasoningProfile = (typeof REASONING_PROFILES)[number];",
    "",
  ];
  for (const [name, def] of Object.entries(schema.$defs)) {
    if (def.description) lines.push(`/** ${def.description} */`);
    if (def.type === "object" && def.properties) {
      const required = new Set(def.required ?? []);
      lines.push(`export interface ${name} {`);
      for (const [key, prop] of Object.entries(def.properties)) {
        if (prop.description) lines.push(`  /** ${prop.description} */`);
        lines.push(`  ${key}${required.has(key) ? "" : "?"}: ${tsType(prop)};`);
      }
      lines.push("}", "");
    } else {
      lines.push(`export type ${name} = ${tsType(def)};`, "");
    }
  }
  return lines.join("\n");
}

// The schema inlines the ReasoningProfile enum at several sites; take the
// EngineInfo default as the source and refuse to generate if any site drifts.
function reasoningProfiles(schema) {
  const defs = schema.$defs;
  const source = defs.EngineInfo.properties.defaultReasoningProfile.enum;
  const sites = {
    "EngineInfo.supportedReasoningProfiles": defs.EngineInfo.properties.supportedReasoningProfiles.items.enum,
    "StartAnalysisRequest.reasoningProfile": defs.StartAnalysisRequest.properties.reasoningProfile.enum,
    "AnalysisRun.reasoningProfile": defs.AnalysisRun.properties.reasoningProfile.enum,
  };
  for (const [site, values] of Object.entries(sites)) {
    if (JSON.stringify(values) !== JSON.stringify(source)) throw new Error(`reasoning profile enum drift at ${site}`);
  }
  return source;
}

function tsType(prop) {
  if (prop.$ref) return prop.$ref.split("/").pop();
  if (prop.const !== undefined) return JSON.stringify(prop.const);
  if (prop.enum) return prop.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (Array.isArray(prop.type)) return prop.type.map((t) => (t === "null" ? "null" : tsType({ ...prop, type: t }))).join(" | ");
  switch (prop.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return `${wrap(tsType(prop.items ?? {}))}[]`;
    case "object":
      if (prop.properties) {
        const required = new Set(prop.required ?? []);
        const fields = Object.entries(prop.properties).map(([k, v]) => `${k}${required.has(k) ? "" : "?"}: ${tsType(v)}`);
        return `{ ${fields.join("; ")} }`;
      }
      if (prop.additionalProperties && typeof prop.additionalProperties === "object") {
        return `Record<string, ${tsType(prop.additionalProperties)}>`;
      }
      return "Record<string, unknown>";
  }
  return "unknown";
}

function wrap(type) {
  return type.includes("|") ? `(${type})` : type;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
  const generated = generate(schema);
  if (process.argv.includes("--check")) {
    const current = readFileSync(outPath, "utf8");
    if (current !== generated) {
      console.error("src/contract.gen.ts is stale; run `npm run generate`");
      process.exit(1);
    }
  } else {
    writeFileSync(outPath, generated);
  }
}
