// Code generated by scripts/generate-types.mjs from
// contracts/public-engine/v1/schema.json. DO NOT EDIT.

export const CONTRACT_SCHEMA = "insight-lab.public-engine";
export const CONTRACT_VERSION = "1";

export const ERROR_CODES = ["INVALID_REQUEST","UNSUPPORTED_CONTRACT_VERSION","NOT_FOUND","IDEMPOTENCY_CONFLICT","IDENTITY_CONFLICT","ANALYSIS_NOT_COMPLETED","ANALYSIS_HAS_NO_HYPOTHESES","MIXED_ANALYSIS_RUNS","INTERNAL"] as const;
export type ContractErrorCode = (typeof ERROR_CODES)[number];

export type ContractVersion = "1";

export type IdempotencyKey = string;

/** Bounded opaque string metadata. Keys match ^[A-Za-z0-9._:-]{1,64}$. In document metadata, keys starting with public_ or analytical_ and the keys dataset_hash and acquisition_manifest are reserved: the engine records that provenance itself. */
export type Metadata = Record<string, string>;

/** Opaque external subject. Insight stores and echoes it but never interprets or branches on it. */
export interface SubjectRef {
  namespace: string;
  id: string;
  type?: string;
}

export interface EngineBuild {
  /** Release version, or UNKNOWN. */
  version: string;
  /** Git commit, or UNKNOWN. */
  commit: string;
  dirty: "true" | "false" | "UNKNOWN";
}

export interface SchemaRef {
  schema: string;
  version: string;
}

export interface EngineInfo {
  contractSchema: "insight-lab.public-engine";
  contractVersion: ContractVersion;
  supportedContractVersions: string[];
  engine: EngineBuild;
  researchArtifact: SchemaRef;
  analyticalArtifact: SchemaRef;
}

export interface CreateSubjectRequest {
  contractVersion: ContractVersion;
  idempotencyKey: IdempotencyKey;
  subject: SubjectRef;
  title?: string;
  metadata?: Metadata;
}

export interface Subject {
  contractVersion: ContractVersion;
  subjectId: string;
  subject: SubjectRef;
  title: string;
  metadata?: Metadata;
  createdAt: string;
}

export interface EvidenceDocument {
  /** Caller's stable reference, unique within a subject. */
  externalRef: string;
  source: "interview" | "review" | "support" | "sales" | "survey" | "job_posting" | "social_post" | "dataset";
  title?: string;
  content: string;
  metadata?: Metadata;
}

/** At least one document or analytical artifact is required. Artifacts follow contracts/analytical-artifact/v1/schema.json. */
export interface AddEvidenceRequest {
  contractVersion: ContractVersion;
  idempotencyKey: IdempotencyKey;
  documents?: EvidenceDocument[];
  analyticalArtifacts?: Record<string, unknown>[];
}

export interface EvidenceItemReceipt {
  externalRef?: string;
  artifactId?: string;
  reproducibilityKey?: string;
  documentId: string;
  status: "CREATED" | "UNCHANGED";
}

export interface EvidenceReceipt {
  contractVersion: ContractVersion;
  subjectId: string;
  documents: EvidenceItemReceipt[];
  analyticalArtifacts: EvidenceItemReceipt[];
}

export interface StartAnalysisRequest {
  contractVersion: ContractVersion;
  idempotencyKey: IdempotencyKey;
  label?: string;
  note?: string;
  semanticAnalysisMode?: "DISCOVERY" | "DATASET_ANALYSIS" | "RESEARCH_REVIEW";
}

/** The run's execution and input snapshots, verbatim. A snapshot the run never recorded is omitted, never sent empty. */
export interface AnalysisProvenance {
  execution?: Record<string, unknown>;
  input?: Record<string, unknown>;
}

export interface AnalysisRun {
  contractVersion: ContractVersion;
  subjectId: string;
  analysisId: string;
  status: "queued" | "running" | "completed" | "failed";
  error?: string;
  label?: string;
  note?: string;
  semanticAnalysisMode?: string;
  executionMode?: "deterministic" | "model_backed";
  engine?: EngineBuild;
  executionFingerprint?: string;
  inputFingerprint?: string;
  provenance?: AnalysisProvenance;
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
}

export interface Observation {
  observationId: string;
  documentId: string;
  externalRef?: string;
  /** Exact text of the source document between startOffset and endOffset (rune offsets). */
  quote: string;
  startOffset: number;
  endOffset: number;
  behavior: string;
  topic?: string;
}

export interface Finding {
  findingId: string;
  kind: "repetition" | "deviation";
  title: string;
  description?: string;
  expectation?: string;
  observationIds: string[];
}

export interface AnalysisResults {
  contractVersion: ContractVersion;
  subjectId: string;
  analysisId: string;
  observations: Observation[];
  findings: Finding[];
  /** The run's recorded evaluation metrics, verbatim. */
  metrics?: Record<string, unknown>;
}

export interface CreateResearchRunRequest {
  contractVersion: ContractVersion;
  idempotencyKey: IdempotencyKey;
  question: string;
  analysisId: string;
  inputReferences?: string[];
  semanticAnalysisMode?: "DISCOVERY" | "DATASET_ANALYSIS" | "RESEARCH_REVIEW";
}

export interface AddedEvidenceLink {
  reference: string;
  gapIds?: string[];
  note?: string;
}

/** Appends a new iteration evaluated on a completed analysis run. Earlier iterations are never modified. */
export interface AppendIterationRequest {
  contractVersion: ContractVersion;
  idempotencyKey: IdempotencyKey;
  analysisId: string;
  question?: string;
  addedEvidence?: AddedEvidenceLink[];
}

export interface ResearchResult {
  contractVersion: ContractVersion;
  subjectId: string;
  researchRunId: string;
  iterationId: string;
  iterationSequence: number;
  analysis: AnalysisRun;
  /** The insight-lab.research-artifact v1 export of the latest iteration, verbatim. Its legacy analysisMode key means execution mode. */
  artifact: Record<string, unknown>;
}

export interface ErrorBody {
  code: "INVALID_REQUEST" | "UNSUPPORTED_CONTRACT_VERSION" | "NOT_FOUND" | "IDEMPOTENCY_CONFLICT" | "IDENTITY_CONFLICT" | "ANALYSIS_NOT_COMPLETED" | "ANALYSIS_HAS_NO_HYPOTHESES" | "MIXED_ANALYSIS_RUNS" | "INTERNAL";
  message: string;
}

export interface ErrorResponse {
  contractVersion: ContractVersion;
  error: ErrorBody;
}
